#!/usr/bin/env bash
# Configure /redirect_me to another page permanently
sudo apt-get -y install nginx
sudo echo "Hello World!" > /var/www/html/index.html

new_string="location /redirect_me {\nrewrite ^/(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n}\n"

sudo sed -i "/# Only/ i $new_string" /etc/nginx/sites-available/default
sudo service nginx restart
